### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vlad0-0** [Stardust-Labs-MC/Terralith#109]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.8

### Mod or datapack version?

Mod (Forge)

### Describe the bug

When trying to generate a flat world, the default world type will be generated

**Comment by catter1** [comment]
Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or in your case: Superflat. Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds. This will be the case until either Mojang fixes the bug, or we spend a *long* time custom coding a mod to fix that.
