### ISSUE TITLE
[Bug] Corruption on server when uploading backup

### ISSUE THREAD

**Issue by RiotSyndrome** [Stardust-Labs-MC/Terralith#110]
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

v2.3.12

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

When we loaded a backup on the server, the server did not launch at first, it corrupted the map, corrupted player data once we get a map up, it basically just implodes on you.

Its a complex issue and from what I know the Terralith World Generation config is where is corrupts, we had to delete that file and a lot of other stuff until we figured out how to get out server back online, but this corruption is _repeatable and gaurenteed_ whenever loading a backup.

While fixable its incredibly difficult to do so, and can _not_ be done by the average person, and could not even be done by me who has some basic level of modding experience.

### Additional context

Details about where the server is hosted and the very specific version of everything, incase its related to the loader or build.

Server is hosted with McProHosting
Fabric Loader 0.14.24 [the highest avalible for said host.]
Terralith v2.3.12

**Comment by catter1** [comment]
To be clear, Terralith is a datapack, and not a mod. The mod is just the datapack version packaged with a `.jar` on the end. However, that should not make a difference, but wanted to point it out since the worldgen is not done in the same way as a traditional mod.

Regardless, loading a backup should **not** be causing these issues, and works fine in every other scenario. Some followup questins to help figure out what went wrong:
- What errors were given the first time the server refused to start up?
- *How* is the backup loaded? It it manually, or done automatically by McProHosting?
- What type of map/playerdata corruption took place?

I should also mention that Terralith - being a datapack - has absolutely no way to touch the playerdata. Player data is stored in the server's `playerdata` folder, which is separate from data about the chunks and world. My only guess is that during the whole process, something else happened to touch the contents of that folder.

**Comment by RiotSyndrome** [comment]
Okay sorry for the response delay I had to pull up our transcript to see exactly what ProHosting said. I totally understand if this is technically not the correct issue, but heres a rundown of that mess from what I understood. [Tldr; A diff group of our sever staff handled this Im just seeing everything after.]

- Backup was loaded automatically by McProHosting
- In order to get into the map we had to remove Terralith or manually reset the level data and something with the Terralith jar was messed with in some way by the MCPH staff. [they did not give the details on that one,,]
From what I understand of it, the terralith data just kinda, gets fucked up and has to be manually edited back in and/or wiped inorder to set that right, and Im not sure if this is a backup issue or a mod issue.

- All of the error codes were so fucking weird that neither me or McProHosting actually understood WHY the error codes were coming up in the way they did.

The playerdata thing is loosely-linked by this main issue, as resolving Terralith did also resolve this, strangely.

Anyways my experience is in modding/plugins and not server handling, so I may be incorrectly seeing a server issue as a mod issue.. But I also know that you know your mod better than we or their staff do, and might be able to identify how to make sure this doesnt happen again?

**Comment by catter1** [comment]
Without knowing the details on how the backup was reinstated or *exactly* what errors happened, I can't really help or give any advice on how to prevent it again. If this ever happens again, please come to us - chances are we have seen the error codes and know what is happening and why, and how to fix it.
