### ISSUE TITLE
[Enhancement] Add a config to disable villages

### ISSUE THREAD

**Issue by asimard1** [Stardust-Labs-MC/Terralith#126]
### Describe your enhancement/improvement, with context and reasoning.

There should be an option to disable villages, as they spawn a lot and they feel a bit too big for vanilla. The castles in the villages are not rare enough, making the game feel less immersive.

**Comment by catter1** [comment]
There is guarenteed to be a single castle for each Fortified Village, since that is the starting piece.

Anyways, Terralith is a datapack, and therefore cannot have a config file. Even the mod version is just the datapack with `.jar` at the end.

However, we do have instructions in our discord on how to remove structures. I will attach screenshots for your convenience.

![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/f575c092-60b7-4dd8-9469-f5abb5620e8d)
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/2a3b16a0-fb6a-4604-b337-1844a5314fe0)

**Comment by asimard1** [comment]
Understood, thank you.
