### ISSUE TITLE
[Bug] No Crystal caves

### ISSUE THREAD

**Issue by ekul6547** [Stardust-Labs-MC/Terralith#127]
### What Minecraft version(s) does this apply to?

1.21

### Project version

v2.5.3

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Crystal caves don't appear on the list when using `/locate biome terralith:`
Looking inside the .jar `/data/terralith/worldgen/biome/`, the crystal_caves.json is completely missing.

### Additional context

Version 2.5.3 from https://modrinth.com/mod/terralith/version/2.5.3

**Comment by catter1** [comment]
Yes, this is 100% intentional. Crystal Caves were removed from generation over 2 years ago. We could never remove the files from the datapack otherwise old worlds would crash. But since it has been a couple of years and Mojang's data fixer has activated by now, issues upgrading would be resolved. So for 1.21, we removed the files. This is also the case for other biomes, such as Ice Caves and Desert Caves.

Out of curiosity, why did you find this? I'm a bit surprised that you were paying attention to a biome that hasn't existed in a very long time.

**Comment by ekul6547** [comment]
> Out of curiosity, why did you find this? I'm a bit surprised that you were paying attention to a biome that hasn't existed in a very long time.

I was looking at the wiki: https://stardustlabs.miraheze.org/wiki/Terralith#Deep_cave_biomes, and Crystal caves are there.
Now looking a bit further though, I can see that on the Crystal Caves page itself has "2.0.9 Scrapped for performance issues".

Maybe on the main page, they should have a strike-through, or an * to indicate they are removed from latest?

**Comment by catter1** [comment]
Gotcha, makes sense. And yeah, I agree with that. It's something I want done on the wiki, but will likely happen once we finish migrating it.
