### ISSUE TITLE
[Enhancement] Add a config to disable Skylands generation

### ISSUE THREAD

**Issue by amycol** [Stardust-Labs-MC/Terralith#139]
### Describe your enhancement/improvement, with context and reasoning.

Skylands look great on usually, however with the addition of some shaders and/or mods like distant horizons they can be an inconvenience, as the large shadows they create can cause significant lag, and they do not look visually appealing with the large render distances that mods like distant horizons enable.

**Comment by catter1** [comment]
Because Terralith is a datapack, it cannot have a config file. Even the mod version, is just the datapack with `.jar` at the end. However we do have a guide on our Discord to remove them if you wish. I have attached screenshots for your convenience.
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/d4944664-bfc8-47f8-8ef1-0450e45b95fb)
![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/d23cf811-f299-4daa-ae57-8043181521c7)
