### ISSUE TITLE
[Bug] Skeleton Spawn Chance lower than expected in Skylands Winter

### ISSUE THREAD

**Issue by Fhill467** [Stardust-Labs-MC/Terralith#162]
### What Minecraft version(s) does this apply to?

1.20 - 1.20.1

### Project version

2.4.5

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

Skeleton/stray spawns rates are much lower in the Skylands Winter biome than in other biomes. According to the Terralith wiki, Stays should have the same spawn chance as Zombies however, only skeletons spawn and their rates are extremely low. 

Keep in mind, if you do see skeletons spawning in the Skylands Winter biome check the biome of the block the spawned on. From my testing, any that do spawn on the Skylands are actually spawning on blocks that register as the biome below the skylands (for instance a cold deep ocean biome). 

I have tested and confirmed this issue on Minecraft 1.20.1 with ONLY Terralith (and Fabric API) installed so there are no mod conflicts going on.

Let me know if you have any questions.

**Comment by catter1** [comment]
Skeletons are not in the code to spawn in Winter Skylands, nor are they intended to. Strays however are. In fact, strays should be about 5% more common than Zombies. If this does not match what you see in practice, keep in ind that Minecraft does have some hardcoded restrictions for some mobs. It is possible Strays do not spawn as well high up or in the other conditions skyalnds provide. But that is out of my expertise.

**Comment by Fhill467** [comment]
Well you were right about Strays having restrictions. Taken from the wiki and confirmed by me 'A stray may spawn directly under the sky' meaning they can ONLY spawn without blocks above them. This means that the ice caves within the Skylands Winter biome will always be devoid of Strays. 

Given the findings above (and assuming I am right) this really isn't a 'bug' so the ticket can technically be closed. 

As a player I would like to say it would be nice to have the Stray spawns fixed in this biome but that may just be out of the developers hands now. Maybe as a trade off the developers could increase the skeleton spawns in the biome as a work around for now. Just putting out ideas is all, at the end of the day I am probably the only one who has ever noticed this 'issue'.

**Comment by catter1** [comment]
I think I like the fact that Strays would spawn instead of skeletons, so although Skeletons are somewhat of a solution, I'd rather not do it.

However, another option might be to find a way to limit mob spawning inside of the caves. I'll have to talk to Starmute more on why he made them hollow, but I don't think there's any purpose for the player to go inside them. If mob spawning is prevented inside, then the only valid mob spawning spaces will be ontop of the island, which will make Strays actually have a chance to spawn at a reasonable level.

But for now, I will close the issue.
