### ISSUE TITLE
[Bug] Using Tectonic and Terralith together results in terrain generation errors.

### ISSUE THREAD

**Issue by zoe-may** [Stardust-Labs-MC/Terralith#171]
### What Minecraft version(s) does this apply to?

1.20 - 1.20.1

### Project version

v2.5.1

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

When I use Tectonic and Terralith together on Mohist, there is an issue with incorrect chunks being generated.
![c5b9780a97ce5cf9e6c62bea9e1c27a2](https://github.com/user-attachments/assets/ec0fbc80-067a-4d49-ac35-895067ce9e06)
![image](https://github.com/user-attachments/assets/851750fc-5263-46b9-a552-92215c626732)

There were many large walls generated, and I know this is due to a conflict between terrain generators. It only returned to normal after I removed Tectonic and deleted the chunks to regenerate them. However, according to the mod descriptions, the versions of Tectonic and Terralith are supposed to be compatible with each other. I’m not sure whose issue this is, so I’ve raised an issue on both sides.

### Additional context

Apollounknowndev/tectonic#230

**Comment by catter1** [comment]
This is not a conflict between Terralith and Tectonic. Rather, this is caused by incorrect installation on a server. The way to fix it is to regenerate the chunks... which is why it fixed itself when you removed Tectonic, since you also regenerated the chunks.

Readd Tectonic, reset the chunks, and it will work fine,

**Comment by zoe-may** [comment]
> This is not a conflict between Terralith and Tectonic. Rather, this is caused by incorrect installation on a server. The way to fix it is to regenerate the chunks... which is why it fixed itself when you removed Tectonic, since you also regenerated the chunks.
> 
> Readd Tectonic, reset the chunks, and it will work fine,

I'm sorry, I'm not very familiar with how to properly configure the server. Is it correct to change "level-type" to the corresponding type? Could you please tell me if there are any other methods to avoid this situation besides deleting Tectonic? I really like the biomes in Terralith, and I also enjoy the terrain in Tectonic, so I would really like to make Terralith compatible with Tectonic.

**Comment by zoe-may** [comment]
Previously, when I regenerated chunks with both mods, it did solve some issues, but there are players who have already established their presence in the corrupted chunks, and I can't delete these chunks. Moreover, I've noticed that this issue often occurs when I create a new world. I'm wondering how I can avoid generating these corrupted chunks when creating a new world.

**Comment by zoe-may** [comment]
> This is not a conflict between Terralith and Tectonic. Rather, this is caused by incorrect installation on a server. The way to fix it is to regenerate the chunks... which is why it fixed itself when you removed Tectonic, since you also regenerated the chunks.
> 
> Readd Tectonic, reset the chunks, and it will work fine,

Previously, when I regenerated chunks with both mods, it did solve some issues, but there are players who have already established their presence in the corrupted chunks, and I can't delete these chunks. Moreover, I've noticed that this issue often occurs when I create a new world. I'm wondering how I can avoid generating these corrupted chunks when creating a new world.

My apologies, my English is not very good, so I may not be expressing myself clearly.

**Comment by catter1** [comment]
> Is it correct to change "level-type" to the corresponding type?

No, you do not have to touch the `level-type`. Leave it as whatever it is for default.


> Could you please tell me if there are any other methods to avoid this situation besides deleting Tectonic?

It's not an issue with Tectonic. Terralith and Tectonic work together out of the box - your situation is due to the world not being created correctly when the server was first started.


>  but there are players who have already established their presence in the corrupted chunks, and I can't delete these chunks.

Yeah, that would be an issue. It depends:
- If the "corrupted chunks" are Terralith/Tectonic, you can copy those chunks. Reset the world, then paste the chunks back in later on the same terrain. You might need tools such as mcaselector or worldedit for this, depending on how big the built area is.
- If the "corrupted chunks" are Vanilla, then it's a bit harder. You can't easily move the chunks into Terralith/Tectonic terrain without it looking poorly. The other option is to paste just the builds themselves, rather than the entire chunk, but this can be difficult.


> I'm wondering how I can avoid generating these corrupted chunks when creating a new world.

This issue only occurs on servers, due to the order things are loaded. You have two options:
- If your server host lets you, manually create the `mods` folder **before** you start the world. Before any chunks are generated. Then add the Tectonic/Terralith mods in before starting the server for the first time.
- This is the method we always recommend, since it's simpler and covers most scenarios: the second you get the server, start it up. Once it finished, stop it immediately. Reset the overworld, add the mods in, then start it again. This is basically what I already recommended to you, but just doing it for the very first time the server is created.


> My apologies, my English is not very good, so I may not be expressing myself clearly.

No worries, there is no issue

**Comment by zoe-may** [comment]
> * If the "corrupted chunks" are Terralith/Tectonic, you can copy those chunks. Reset the world, then paste the chunks back in later on the same terrain. You might need tools such as mcaselector or worldedit for this, depending on how big the built area is.

Based on my observations, it seems that the corrupted chunks are being generated by Tectonic. I'm finding it difficult to describe with words, but perhaps I can show you some pictures to illustrate the issue.
![2024-10-05_21 46 10](https://github.com/user-attachments/assets/c25c1143-5f9f-4f90-aa62-2f1d2de64e89)
In this picture, I'm showing what I refer to as a "corrupted chunk." It appears smoother and has characteristics typical of Tectonic. I call it a "corrupted chunk" because when I regenerate this area, it generates new terrain that replaces the Tectonic features.

![2024-10-05_21 46 22](https://github.com/user-attachments/assets/d8a1683a-7ca3-49d6-8bb5-dca1bd16b34a)
In this picture, I'm showing the terrain of a normal chunk. It's relatively less smooth, and regenerating the chunk by deleting it does not change the terrain.

![2024-10-05_21 46 30](https://github.com/user-attachments/assets/af8711ab-1204-497c-ab3e-a8085f736ac7)
And this is the boundary between the two types of chunks, where it's clearly visible that the terrain was generated by different terrain generators.

----
It's precisely because of this that I suspect there might be compatibility issues between Tectonic and Terralith on Mohist, although this is just my personal judgment. I hope this information is helpful to you.

**Comment by catter1** [comment]
My answer still stands: there is no compatibility issue, this is just an issue with how the mods were installed and world generated.

My point about the "corrupted chunks": If your players are building on chunks generated with Tectonic, then it's very easy to save those chunks. But if they were building on the chunks generated without Tectonic, then it's a bit more difficult. This assumes you are okay with resetting the entire overworld to fix the issue, and then re-pasting the builds.

**Comment by zoe-may** [comment]
> My answer still stands: there is no compatibility issue, this is just an issue with how the mods were installed and world generated.
> 
> My point about the "corrupted chunks": If your players are building on chunks generated with Tectonic, then it's very easy to save those chunks. But if they were building on the chunks generated without Tectonic, then it's a bit more difficult. This assumes you are okay with resetting the entire overworld to fix the issue, and then re-pasting the builds.

Okay, I think I understand now. Thank you very much for your answer!
