### ISSUE TITLE
[Question] [Terralith] Disabling large caverns/noise caves manually.

### ISSUE THREAD

**Issue by RionEV** [Stardust-Labs-MC/Terralith#174]
I've actually managed to do this once before perhaps a year ago but I cannot for the life of me remember what I changed; if anyone has better documentation, how do I remove large noise caves from generation? I understand from looking through closed issues that better documentation of each component is planned but I am yet to find it here.
As far as I remember I think what needs to be done is removing one of the outer arguments from **final_density.json** under **..\data\minecraft\worldgen\density_function\overworld\noise_router\**, but I'm comparing my modified version from a while ago to the most recent update and can't find the change I made any more.

Alternatively, some info on which specific component of final_density controls large cave generation would be helpful. I am not sure but I *think* "**minecraft:overworld/sloped_cheese**" is responsible for that. Can anyone confirm?

I'm fine with "minecraft:overworld/cave/entrances" features being generated because they make interesting furrows that are less troublesome than the titanic fissures left by the cliffs-and-caves terrain generation; my hope is to go back to a more 1.7.10 style of terrain generation, with regular noodle caves and old-style ravines only, which means getting those large noise caves removed.

**Comment by catter1** [comment]
Apologies for missing this issue - it was created when I was away from my machine for a while, and I must have accidentally dismissed the notification.

If you still need help with editing Terralith's noise caves, I will point you to our [discord](https://discord.gg/stardustlabs), where we have a channel dedicated for people working on worldgen. Mainly because I treat our Github as an issue tracker, rather than questions on editing. Also because I am not qualified to help you with this question.

**Comment by RionEV** [comment]
That's a shame,
