### ISSUE TITLE
[Bug] Lang missing (MC: 1.20.1, Terralith: v2.5.4 .jar)

### ISSUE THREAD

**Issue by FinalBossJ** [Stardust-Labs-MC/Terralith#175]
### What Minecraft version(s) does this apply to?

1.20 - 1.20.1

### Project version

v2.5.4

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

Language files seem to be missing, noticeable using mods that display biome names i.e. Xaero's World Map.
Temporarily solved by manually adding en-us.json with biome key-name pairs to /assets/terralith/lang.

![image](https://github.com/user-attachments/assets/56ee500d-9395-4943-9a3f-19047f422ca6)

Minecraft: 1.20.1
Terralith.jar: 2.5.4
Modloader: Both Forge and Fabric

**Comment by Jan-Arbus** [comment]
Now the lang files have been moved to the [spackles resourcepack](https://modrinth.com/resourcepack/sparkles). So I guess it's not a bug.

**Comment by catter1** [comment]
It both is and is not a bug. You are correct that the translations are in the Sparkles resourcepack. However, I have historically merged the translations into the mod verion of Terralith upon building it. The issue is that right now, my automatic mod building pipeline is broken/under repair, so I have to manually build the mod. Merging the translations is a bit of a pain (and I forget), so I have been building the mod version for the past few months without translations. Whenever I have the time to fix my pipeline, the mod version will once again have translations.
