### ISSUE TITLE
[Enhancement] Add an option to leave vanilla biomes untouched

### ISSUE THREAD

**Issue by User4716** [Stardust-Labs-MC/Terralith#186]
### Terralith alters the look and feel of some vanilla biomes; that's the main factor that led me away from this mod (for now), I simply miss the classic biomes too much
So would it be possible to provide us with a toggle to simply choose if we want our vanilla biomes to be changed?

**Comment by catter1** [comment]
As Terralith is a datapack, it is not easily possible to add a toggle (much less any sort of config).

If you want to edit the datapack/mod for your own personal use:
- Unzip Terralith
- Navigate to `data/minecraft/worldgen/biome`
- Delete every file in this folder (this removes Terralith's changes)
- Rezip the datapack/mod back up

I should specify, this will not change terrain in those biomes back to vanilla. That is practically impossible with Terralith. There may also be a *couple* of small changes to some foliage in vanilla biomes, since Terralith overrides a couple of them. But this is uncommon.
