### ISSUE TITLE
How to uninstall mod?

### ISSUE THREAD

**Issue by allanonmage** [Stardust-Labs-MC/Terralith#21]
I'm using MultiMC 5 running a 1.19.2 world, and disabled the mod.  I used MCA Selector to prune the chunks that Terralith affected, and was going to try my test world without Terralith, but I get an error when launching the world about an issue with datapacks.  Re-enabling the mod lets me back in the world.

An internet search found no relevent results, so here I am.

Do I need to remove some files or folders?  I have several other mods that I'm playtesting, including related mods like Structory, nullscape, and Incendium, and terrablender, which I think is a prerequisite for one of these Starmute mods.  I'd like to keep the other ones and just remove Terralith.

I was able to copy my prod folder and replace it with the backup of the world from the server, and then re-add the mods and datapacks I'm experimenting with, and that loaded fine.  Literally CTRL+A and unselect Terralith.  Sounds like maybe I missed some chunks maybe?  MCA Selector selected everything with less than 5 minutes though, which appeared to be all the relevent ones.

**Comment by catter1** [comment]
First off, just to make it clear, Terrablender is *NOT* a requirement for Stardust Labs mods. In fact, we highly discourage it. It is only needed when using Terralith alongside other worldgen mods, such as WWOO, BoP, or BYG.

Anyways, the reason your world will not load is due to the Terralith biomes still being stored in the vanilla registry, which is found in your `level.dat`. There are two ways to fix this:
1. Hard way: remove every single Terralith biome entry from your `level.dat`. There are thousands of entries.
2. Easy way: just reset your `level.dat` (and `level.dat_old`). This will also reset a couple of things, such as your dragon fight progress (which gateways are opened, if the dragon should grant the full xp, etc), gamerules, game time, and other similar things. Not a huge deal, but it's a lot easier to just change your gamerules again than it is to remove Terralith biomes from your `level.dat

**Comment by meedstrom** [comment]
Ah, resetting `level.dat` is what is meant by this line in the [front page](https://modrinth.com/datapack/terralith)?

> Do not add this to an existing world - reset yours first, or use a new world

Also just to ask, could OP have left the "Terralith-affected chunks" in, and removed Terralith anyway? If the biomes all change to the apparently default plains biome, I assume that does not actually destroy any blocks.

**Comment by catter1** [comment]
> Ah, resetting level.dat is what is meant by this line in the [front page](https://modrinth.com/datapack/terralith)?

No, that is a different issue. The front page discourages adding Terralith to an existing world because it will cause ugly borders between old Vanilla chunks and new Terralith chunks. Because you are *adding* biomes to the world, there are no crash issues or anything you need to fix with the `level.dat`. The issue comes when you do the reverse, and remove biomes from a world.

> Also just to ask, could OP have left the "Terralith-affected chunks" in, and removed Terralith anyway? If the biomes all change to the apparently default plains biome, I assume that does not actually destroy any blocks.

No, OP could not have. The issue is not blocks, as Terralith does not add any custom blocks. Instead, biomes do *not* change to a default plains biome. When the game loads without Terralith, it sees biomes already generated in the world, but it no longer knows what those biomes are. Therefore, the game freaks out and prevents the world from loading.

**Comment by meedstrom** [comment]
Thank you for the explanation!
