### ISSUE TITLE
[Bug] "World type" option doesn't make a difference

### ISSUE THREAD

**Issue by RobinYH** [Stardust-Labs-MC/Terralith#35]
### What Minecraft version(s) does this apply to?

1.18.2, 1.19.x, 1.19.4, 1.20

### Project version

2.4.1

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

The "world type" option on world creation doesn't actually change how the world is created. Maybe make terralith's world generation its own world type to make default world types accessible without uninstalling the mod.

### Additional context

I only tested this on 1.20, but I'm sure it's the same on other versions.

**Comment by catter1** [comment]
This is completely intentional. Terralith is a datapack (even the mod is just a datapack packaged as a mod), and therefore cannot have worldtypes defined. You just plug it in and it will automatically work.

In order to use default world types, you will have to disable the mod beforehand. This will be the case until this [Minecraft Bug](https://bugs.mojang.com/browse/MC-260949) is fixed.
