### ISSUE TITLE
Limiting Vanilla = Better Performance/Popularity [Enhancement]

### ISSUE THREAD

**Issue by TheIrishStud** [Stardust-Labs-MC/Terralith#40]
### Describe your enhancement/improvement, with context and reasoning.

Reconfigure Terralith so it removes all growing bamboo, swamp/jungle vines, and glow berry vines, from world generation, make bamboo, swamp/jungle vines, and glow berry vines all obtainable items only through trades or chests, and watch world generation performance across multiple spectrums of low/mid-tier hardware increase exponentially. Always wondered why the game ran so smoothly until I entered a jungle or a swamp biomes and I started experimenting to increase my performance. Low and behold my surprise when performance increased after yeeting and deleting everything that doesn't have a set growth size limit. I know this is a huge change to ask for but when you have to go 5-7+ years with a single outdated low/mid-tier PC you'll be surprised how many people will be willing to take the temporary visual downgrade to world generation if it means more players can run smoothly with a 4gb GPU at maximum render distance for bigger base builds/ideas. Always wanted to eventually overhaul and decorate all the biomes myself but everything with no set growth size limit severely hinders game performance. Banish all vines, bamboo, and glow berries to the shadow realm (chests/trades) and watch how fast world generation performance increases.

Or at the very least make a new mod that gives us the ability to yeet and delete vines, bamboo, and glow berries for increased world generation performance by banishing them to chests and trades? New content means nothing when world generation performance continues to get worse with each passing update. Please at the very least give this a shot in the background because nothing grinds my gears like watching a vast plethora of quality entertainment getting passed up because nobody has bothered to try the obvious. The obvious being the yeeting and deleting of content that not even Mojang or Microsoft is willing to address or update for quality of life performance enhancements because they would rather make the problem worse. Forcing everyone who wants to continue to play Minecraft into getting newer, more expensive hardware, when simple changes are all that is needed to increase the average player experience/performance in a positive way.

**Comment by Apollounknowndev** [comment]
For bamboo and glow berries, they can just be reconfigured so they always grow at the maximum age and won't grow any further.

**Comment by catter1** [comment]
This is a valid complaint, and what you said about a config is technically possible. However, the better solution would to have someone make a performance mod for this. The mod could theoretically be configured to etiher do what Apollo said, remove *all* the things you mentioned, or anything in between.

Because of that, I will close this issue. I have no clue who may be interested in creating a mod like this, but I will keep it in mind if I ever spot an opportunity. Modifying base Terralith for this purpose is simply out of the question, and any time spent on making a config for this would be better spent making the mod, so it can be applied to *any* worldgen mod/datapack, including Vanilla.
