### ISSUE TITLE
[Bug] Superflat is broken

### ISSUE THREAD

**Issue by NovaViper** [Stardust-Labs-MC/Terralith#43]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.3

### Mod or datapack version?

Mod (Forge)

### Describe the bug

When trying to generate a Super flat world, it instead generates a standard world, it seems to completely ignore the flag entirely. 

### Additional context

I'm also running Tectonic v2.1

**Comment by catter1** [comment]
This is unfortunately intentional. Terralith is a datapack (even the mod is just a datapack packaged as a mod), and therefore cannot have worldtypes defined. You just plug it in and it will automatically work.

In order to use default world types, you will have to disable the mod beforehand. This will be the case until this [Minecraft Bug](https://bugs.mojang.com/browse/MC-260949) is fixed.
