### ISSUE TITLE
[Bug] Superflat - Void not working with terralith installed

### ISSUE THREAD

**Issue by KiloTheNeko** [Stardust-Labs-MC/Terralith#51]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.5

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

![2023-10-08_12 41 56](https://github.com/Stardust-Labs-MC/Terralith/assets/65069111/f1f2f921-0c66-41c2-9e77-9432bac8940f)
this is the super flat i generated.... does this look like the superflat void world ?

**Comment by catter1** [comment]
Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or in your case: Superflat. Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds. This will be the case until either Mojang fixes the bug, or we spend a *long* time custom coding a mod to fix that.
