### ISSUE TITLE
Superflat worlds generate as normal worlds [Bug]

### ISSUE THREAD

**Issue by Variann** [Stardust-Labs-MC/Terralith#59]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.7

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

1. Go into Create New World menu.
2. Set "World Type" to Superflat
3. Create world.

The world will generate chunks as if it is a normal world.

### Additional context

Disabling the mod fixed it, then loading a world made without the mod active (I was checking if the world maybe needed a flag to be set and the bug might be that the flag was not being applied) and generating new chunks caused chunks to be loaded as if it was a normal world.

**Comment by catter1** [comment]
Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or in your case: Superflat. Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds. This will be the case until either Mojang fixes the bug, or we spend a *long* time custom coding a mod to fix that.
