### ISSUE TITLE
[Bug] Superflat worlds cannot be created while the mod is installed

### ISSUE THREAD

**Issue by wan6845** [Stardust-Labs-MC/Terralith#70]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.8

### Mod or datapack version?

Mod (Forge)

### Describe the bug

As the title says, Superflat worlds cannot be made while the mod is installed. I haven't tested with other world types, but they might not work either. If you try to make a Superflat world the world just generates normally.

**Comment by catter1** [comment]
Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or in your case: Superflat. Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds. This will be the case until either Mojang fixes the bug, or we spend a *long* time custom coding a mod to fix that.

**Comment by GeometryLegendX** [comment]
one verry simple fix:
download a superflat map from planetminecraft.net or this map i found on curseforge: https://www.curseforge.com/minecraft/worlds/redstone-world-redstone-ready made for a older version but i tested, it works, just download and put it in your saves folder. remove the middle structure and boom, fixed
.. just dont go in spectator and ook a deep underground, in later versions the bottom of the world was extended so new terrain will be generated(expect GIANT lava pools from terralyth there or smth like that)

**Comment by midvightmirage** [comment]
terralith isnt a mod? what in the
why is it marked as a mod if its a datapack

**Comment by catter1** [comment]
> Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod)

**Comment by AshN1ght** [comment]
Still not fixed.

**Comment by catter1** [comment]
Are you using the **mod** version 2.6.0 or higher? It is only fixed in those versions, which is currently for 1.21.11 and 26.1.x.

**Comment by AshN1ght** [comment]
> Are you using the **mod** version 2.6.0 or higher? It is only fixed in those versions, which is currently for 1.21.11 and 26.1.x.

using 1.20.1 fabric version.
