### ISSUE TITLE
The mod pretty much just ignores the generation changing settings

### ISSUE THREAD

**Issue by a-fan9823** [Stardust-Labs-MC/Terralith#90]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.11

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

as the title implies, it kinda just ignores superflat world setting/single biome settting, I'm not sure about any other settings at the moment.

### Additional context

https://youtu.be/mSkdpN2ghyU

**Comment by a-fan9823** [comment]
it'll take a while for the hd version to process.

**Comment by catter1** [comment]
Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or in your case: Superflat. Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds. This will be the case until either Mojang fixes the bug, or we spend a *long* time custom coding a mod to fix that.

**Comment by a-fan9823** [comment]
oh ok, got it
