### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SadEPa0628** [Stardust-Labs-MC/Terralith#91]
### What Minecraft version(s) does this apply to?

1.18.2, 1.19.x, 1.19.4, 1.20

### Project version

v2.4.11

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

Select Superflat World when creating a world, Terralith will still generate natural terrain(Text translated from Chinese, may contain errors)

**Comment by catter1** [comment]
Terralith is a datapack (yes, even the mod version - it is a datapack packaged as a mod). Due to [this Minecraft bug](https://bugs.mojang.com/browse/MC-260949), worldgen datapacks cannot support other world types, such as Large Biomes, Amplified, or in your case: Superflat. Although it is a pain, you will need to disable Terralith when making **and** using superflat worlds. This will be the case until either Mojang fixes the bug, or we spend a *long* time custom coding a mod to fix that.
