### ISSUE TITLE
[Bug] Neoforge game v. 1.20.4

### ISSUE THREAD

**Issue by LeXus21251** [Stardust-Labs-MC/Terralith#99]
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.4.10

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Is this mod compatible with neoforge? in mod browser its labeled as such

**Comment by catter1** [comment]
It is not. It should not say it is compatible, where does it say so?

**Comment by toruPuchuu** [comment]
If it helps, ATLauncher quite happily adds Terralith (from Curseforge) to my custom 1.20.4 Neoforge modpack, while Terralith (from Modrinth) correctly returns an error, "No versions found for this mod".

Update: If you go to the Curseforge website for mods, select Neoforge and then search for Terralith, the search results show Neoforge compatability.

**Comment by catter1** [comment]
That's an issue on Curseforge's end. A while ago in error, I flagged one of the versions as Neoforge compatible. I have since then removed the flag, and no versions are marked as compatible with Neoforge.

Curseforge must have cached that information, and never updated it. I will close this issue since I did not receive a response from OP in the past three weeks, and it looks like we have found what may have caused it.

![image](https://github.com/Stardust-Labs-MC/Terralith/assets/63272345/9808e702-b6fe-4013-aafd-591ccf382233)
